spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lingotlow_dev
    username: lingotlow
    password: lingotlow_dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    host: localhost
    port: 6379
